<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Doctrine\Bundle\MongoDBBundle\Command\TailCursorDoctrineODMCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/doctrine/mongodb-odm-bundle/Command/TailCursorDoctrineODMCommand.php';

return $this->services['Doctrine\\Bundle\\MongoDBBundle\\Command\\TailCursorDoctrineODMCommand'] = new \Doctrine\Bundle\MongoDBBundle\Command\TailCursorDoctrineODMCommand();
