<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppBundleDocumentUserHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="int") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['email']) || (! empty($this->class->fieldMappings['email']['nullable']) && array_key_exists('email', $data))) {
            $value = $data['email'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['email']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['email']->setValue($document, $return);
            $hydratedData['email'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['name']) || (! empty($this->class->fieldMappings['name']['nullable']) && array_key_exists('name', $data))) {
            $value = $data['name'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['name']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['role']) || (! empty($this->class->fieldMappings['role']['nullable']) && array_key_exists('role', $data))) {
            $value = $data['role'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['role']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['role']->setValue($document, $return);
            $hydratedData['role'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['password']) || (! empty($this->class->fieldMappings['password']['nullable']) && array_key_exists('password', $data))) {
            $value = $data['password'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['password']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['password']->setValue($document, $return);
            $hydratedData['password'] = $return;
        }

        /** @Field(type="timestamp") */
        if (isset($data['created']) || (! empty($this->class->fieldMappings['created']['nullable']) && array_key_exists('created', $data))) {
            $value = $data['created'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['created']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['created']->setValue($document, $return);
            $hydratedData['created'] = $return;
        }

        /** @Field(type="timestamp") */
        if (isset($data['updated']) || (! empty($this->class->fieldMappings['updated']['nullable']) && array_key_exists('updated', $data))) {
            $value = $data['updated'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['updated']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['updated']->setValue($document, $return);
            $hydratedData['updated'] = $return;
        }
        return $hydratedData;
    }
}