<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppBundleDocumentPostAddHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="int") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['postby'])) {
            $reference = $data['postby'];
            $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['postby'], $reference);
            $mongoId = ClassMetadataInfo::getReferenceId($reference, $this->class->fieldMappings['postby']['storeAs']);
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['postby']->setValue($document, $return);
            $hydratedData['postby'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['like']) || (! empty($this->class->fieldMappings['like']['nullable']) && array_key_exists('like', $data))) {
            $value = $data['like'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['like']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['like']->setValue($document, $return);
            $hydratedData['like'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['postname']) || (! empty($this->class->fieldMappings['postname']['nullable']) && array_key_exists('postname', $data))) {
            $value = $data['postname'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['postname']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['postname']->setValue($document, $return);
            $hydratedData['postname'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['post']) || (! empty($this->class->fieldMappings['post']['nullable']) && array_key_exists('post', $data))) {
            $value = $data['post'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['post']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['post']->setValue($document, $return);
            $hydratedData['post'] = $return;
        }

        /** @Field(type="timestamp") */
        if (isset($data['created']) || (! empty($this->class->fieldMappings['created']['nullable']) && array_key_exists('created', $data))) {
            $value = $data['created'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['created']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['created']->setValue($document, $return);
            $hydratedData['created'] = $return;
        }

        /** @Field(type="timestamp") */
        if (isset($data['updated']) || (! empty($this->class->fieldMappings['updated']['nullable']) && array_key_exists('updated', $data))) {
            $value = $data['updated'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['updated']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['updated']->setValue($document, $return);
            $hydratedData['updated'] = $return;
        }
        return $hydratedData;
    }
}