<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_mongodb.odm.default_connection' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Connection.php';
include_once $this->targetDirs[3].'/vendor/doctrine/common/lib/Doctrine/Common/EventManager.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php';

return $this->services['doctrine_mongodb.odm.default_connection'] = new \Doctrine\MongoDB\Connection('mongodb://localhost:27017', [], ${($_ = isset($this->services['doctrine_mongodb.odm.default_configuration']) ? $this->services['doctrine_mongodb.odm.default_configuration'] : $this->load('getDoctrineMongodb_Odm_DefaultConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine_mongodb.odm.event_manager']) ? $this->services['doctrine_mongodb.odm.event_manager'] : ($this->services['doctrine_mongodb.odm.event_manager'] = new \Symfony\Bridge\Doctrine\ContainerAwareEventManager($this))) && false ?: '_'}, []);
