<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Doctrine\Bundle\MongoDBBundle\Command\GenerateRepositoriesDoctrineODMCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/doctrine/mongodb-odm-bundle/Command/DoctrineODMCommand.php';
include_once $this->targetDirs[3].'/vendor/doctrine/mongodb-odm-bundle/Command/GenerateRepositoriesDoctrineODMCommand.php';

return $this->services['Doctrine\\Bundle\\MongoDBBundle\\Command\\GenerateRepositoriesDoctrineODMCommand'] = new \Doctrine\Bundle\MongoDBBundle\Command\GenerateRepositoriesDoctrineODMCommand(${($_ = isset($this->services['doctrine_mongodb']) ? $this->services['doctrine_mongodb'] : $this->getDoctrineMongodbService()) && false ?: '_'});
